sudo: required
services:
    - docker
before_install:
    - docker build -t deeksha021chaudhary/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run deeksha021chaudhary/react-test npm test -- --watchAll=false
after_success:
    - docker build -t deeksha021chaudhary/multi-client ./client 
    - docker build -t deeksha021chaudhary/multi-nginx ./nginx
    - docker build -t deeksha021chaudhary/multi-server ./server
    - docker build -t deeksha021chaudhary/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
    - docker push deeksha021chaudhary/multi-client
    - docker push deeksha021chaudhary/multi-nginx
    - docker push deeksha021chaudhary/multi-server
    - docker push deeksha021chaudhary/multi-worker

    
